### ISSUE TITLE
camera transformation broken in tracking

### ISSUE THREAD

**Issue by mixmixmix** [ctorney/uavTracker#22]
Clearly doesn't work on the most recent version. 
https://youtu.be/sMf9-c7rZ8g
I can't find anything wrong in the code I changed, so I will try to see visually if camera transforms look correct when just applied to the video in the original frame of reference.

Ideas welcome.

**Comment by mixmixmix** [comment]
I tested code for calculating transformations and it works correctly apart from when movement is too rapid:
https://www.youtube.com/watch?v=b1AlGA5Fq-M

**Comment by aakanksharathore** [comment]
Is this video for skip1 or skip5? Looks like skip5 to me. We were getting
similar id switches in skip5 and then decided to go woth skip1, which is
giving correct tracking.

*Namastey!*

Akanksha Rathore
PhD scholar
CES, Indian Institute of Science
Bangalore 560012
website: https://sites.google.com/view/akanksha-rathore
twitter: akanksha_ak5 <https://twitter.com/akanksha_ak5>

**Comment by mixmixmix** [comment]
This is skip-1

**Comment by mixmixmix** [comment]
That was not the case for the files which raised this issue:
~~Ok, got it... I should have read my own bloody logs:~~
```
Loading transformations from ../data/blackbucks//tracks/21MarchMor_02_03_MAT.npy
:: oh dear! :: No transformations found.
[========            ] 41% 11700/280482019-06-30 14:12:57.274439: I tensorflow/stream_executor/platform/default/dso_loader.cc:161] successfully opened CUDA library libcudnn.so.7 locally
[==============      ] 73% 20701/28048
```
The transformations file was not loaded and hence camera motion wasn't compensated for!

**Comment by mixmixmix** [comment]
Though that might be the case with only some of the videos, most of them have transformations...

**Comment by ctorney** [comment]
the transforms array is there 
./data/blackbucks//tracks/21MarchMor_02_03_MAT.npy
at least it is in my data directory

**Comment by aakanksharathore** [comment]
I checked the outputs for two videos on our systems. Tracking is fine
during camera movement but yes there are some ID fluctuations abruptly in
the duration when camera is stable.

*Namastey!*

Akanksha Rathore
PhD scholar
CES, Indian Institute of Science
Bangalore 560012
website: https://sites.google.com/view/akanksha-rathore
twitter: akanksha_ak5 <https://twitter.com/akanksha_ak5>
