### ISSUE TITLE
Understanding training metrics

### ISSUE THREAD

**Issue by mixmixmix** [ctorney/uavTracker#37]
@ctorney, I fail to understand what are the `concat_X_loss` and `concat_X_accuracy` that we are outputting while training (where X in [2,3,4]). I think it is something we added to see changes at different... layers? Before I go on a wild goose chase, maybe you have some ideas. Here is an example output from tensorboard:
![Screenshot_2022-11-17_13-21-32](https://user-images.githubusercontent.com/9990867/202458237-3af6c6b6-c0ba-4746-8cfa-8dbf663392ea.png)

**Comment by ctorney** [comment]
I think the 3 values correspond to the 3 different scales of loss values - yolo returns a list of 3 losses for each set of grids (large, medium, small). I'm guessing that keras then uses these values when constructing the training metrics but not sure where the names come from

**Comment by mixmixmix** [comment]
Ok, thanks! That makes sense. For now I'm focussing on overall loss and accuracy which should be enough.
